"use client";
import {useEffect,useMemo,useState} from "react";
type Phase="FUEL"|"PRE-SQUEEZE"|"ACTIVE"|"INVALIDATED"|"LIQUIDITY";
type Row={ticker:string;price:number;breakout:number;rvol:number;si:number;dtc:number;ctb:number;avail:number;ftd:number;svd:number;phase:Phase;freshness:string;updatedAt:number;provider:string};
const badge=(p:Phase)=>p==="ACTIVE"?"border-emerald-500 text-emerald-300":p==="PRE-SQUEEZE"?"border-amber-500 text-amber-300":p==="LIQUIDITY"?"border-cyan-500 text-cyan-300":p==="INVALIDATED"?"border-rose-500 text-rose-300":"border-slate-500 text-slate-300";
export default function Home(){
 const[rows,setRows]=useState<Row[]>([]),[sel,setSel]=useState("BBAI"),[tab,setTab]=useState("board"),[loading,setLoading]=useState(true),[err,setErr]=useState("");
 const load=async()=>{try{setLoading(true);const r=await fetch("/api/market",{cache:"no-store"});const j=await r.json();setRows(j.signals);setErr(j.error||"")}catch(e){setErr(String(e))}finally{setLoading(false)}};
 useEffect(()=>{load();const id=setInterval(load,10000);return()=>clearInterval(id)},[]);
 const cur=rows.find(r=>r.ticker===sel)||rows[0];const counts=useMemo(()=>{const c={FUEL:0,"PRE-SQUEEZE":0,ACTIVE:0,INVALIDATED:0,LIQUIDITY:0} as Record<Phase,number>;rows.forEach(r=>c[r.phase]++);return c},[rows]);
 return <main className="min-h-screen"><header className="border-b border-slate-800 p-6"><div className="mx-auto max-w-[1500px] flex justify-between"><div><div className="text-xs tracking-[.3em] text-cyan-300">FICKLE CREATION STUDIOS</div><h1 className="text-3xl font-semibold">Squeeze Race</h1><p className="text-sm text-slate-400">Live market adapter + deterministic trigger engine.</p></div><div className="text-right text-xs">{loading?"REFRESHING":rows[0]?.freshness==="LIVE"?"● LIVE":"● "+(rows[0]?.freshness||"WAITING")}<div className="text-slate-500 mt-1">10s refresh</div></div></div></header>
 <div className="mx-auto max-w-[1500px] p-6">{err&&<div className="mb-4 border border-amber-800 bg-amber-950/30 p-3 rounded-lg text-sm text-amber-200">{err}. Live fields require a server-side POLYGON_API_KEY; lagged squeeze metrics remain configured separately.</div>}
 <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-5">{(["FUEL","PRE-SQUEEZE","ACTIVE","INVALIDATED","LIQUIDITY"] as Phase[]).map(p=><div className="panel p-4" key={p}><div className="text-xs text-slate-500">{p}</div><div className="text-2xl">{counts[p]||0}</div></div>)}</div>
 <div className="flex gap-2 mb-5">{[["board","Trigger Board"],["rules","Exact Rules"],["sim","$500 Simulator"]].map(x=><button key={x[0]} onClick={()=>setTab(x[0])} className={"rounded-lg px-4 py-2 text-sm "+(tab===x[0]?"bg-cyan-900":"bg-slate-900 text-slate-400")}>{x[1]}</button>)}</div>
 {tab==="board"&&cur?<div className="grid xl:grid-cols-[1fr_340px] gap-5"><section className="panel overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Ticker","Phase","Price / Breakout","RVOL","SI","DTC","CTB","Avail","FTD/Float","SV Div.","Fresh"].map(h=><th className="p-3 text-xs text-slate-500 whitespace-nowrap" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.ticker} onClick={()=>setSel(r.ticker)} className={"border-t border-slate-800 cursor-pointer "+(sel===r.ticker?"bg-slate-900":"")}><td className="p-3 font-semibold mono">{r.ticker}</td><td className="p-3"><span className={"border rounded-full px-2 py-1 text-[10px] "+badge(r.phase)}>{r.phase}</span></td><td className="p-3 mono">USD {r.price.toFixed(2)} / {r.breakout.toFixed(2)}</td><td className="p-3 mono">{r.rvol.toFixed(2)}x</td><td className="p-3 mono">{r.si.toFixed(1)}%</td><td className="p-3 mono">{r.dtc}</td><td className="p-3 mono">{r.ctb.toFixed(1)}%</td><td className="p-3 mono">{r.avail.toLocaleString()}</td><td className="p-3 mono">{r.ftd.toFixed(2)}%</td><td className="p-3 mono">{r.svd.toFixed(1)}pp</td><td className="p-3 text-xs text-slate-500">{r.freshness}</td></tr>)}</tbody></table></section><aside className="panel p-5"><div className="text-xs text-slate-500">SELECTED</div><h2 className="text-3xl mono mt-1">{cur.ticker}</h2><span className={"inline-block border rounded-full px-2 py-1 text-[10px] mt-2 "+badge(cur.phase)}>{cur.phase}</span><div className="mt-5 space-y-3">{[["Price","USD "+cur.price.toFixed(2)],["Breakout","USD "+cur.breakout.toFixed(2)],["RVOL",cur.rvol.toFixed(2)+"x"],["SI",cur.si.toFixed(1)+"%"],["DTC",String(cur.dtc)],["CTB",cur.ctb.toFixed(1)+"%"],["Shares available",cur.avail.toLocaleString()],["FTD / float",cur.ftd.toFixed(2)+"%"],["SV divergence",cur.svd.toFixed(1)+"pp"]].map(x=><div className="flex justify-between border-b border-slate-800 pb-2 text-sm" key={x[0]}><span className="text-slate-500">{x[0]}</span><span className="mono">{x[1]}</span></div>)}</div><p className="text-xs text-slate-500 mt-5">Price/volume can be live through the configured provider. SI/FTD/CTB/availability are not inferred from price and remain explicitly sourced or unavailable.</p></aside></div>:
 tab==="rules"?<div className="grid md:grid-cols-2 gap-4">{[["Squeeze fuel","SI >= 20% AND DTC >= 5"],["Pre-squeeze","Price >= breakout AND RVOL >= 2x AND one stress signal: CTB >= 5%, availability <= 500k, FTD >= 1% float, or SV divergence >= 5pp"],["Active mechanics","Price >= breakout AND RVOL >= 3x AND CTB >= 5% AND one: availability <= 250k, CTB >= 10%, FTD >= 1%, or SV divergence >= 5pp"],["Invalidated","Price <= 95% of breakout OR SI < 20% OR material dilution/resale event"],["GYGY liquidity","Market cap < $25M AND RVOL >= 3x AND float turnover >= 25%; separate from classic SI squeeze logic"],["Data integrity","No missing provider field is silently converted into a positive squeeze signal. Provider and freshness are carried with every market observation."]].map(x=><div className="panel p-5" key={x[0]}><div className="text-xs text-cyan-300 uppercase">{x[0]}</div><p className="text-sm leading-6 text-slate-300 mt-3">{x[1]}</p></div>)}</div>:
 <div className="grid md:grid-cols-3 gap-5">{[["Strategy A","Squeeze Waiting Room","USD 350 equity + USD 150 trailing-stop cash buffer"],["Strategy B","Catalyst Alert","Keep USD 500 liquid; example trigger volume >3x average plus CTB >5%, then evaluate VWAP breakout"],["Strategy C","GYGY Liquidity","Example USD 100 max speculative allocation; 5–8% stop; liquidity event, not classic squeeze"]].map(x=><div className="panel p-5" key={x[0]}><div className="text-xs text-cyan-300">{x[0]}</div><h2 className="text-xl mt-2">{x[1]}</h2><p className="text-sm text-slate-400 mt-3">{x[2]}</p></div>)}</div>}
 <footer className="text-xs text-slate-500 mt-8">Research dashboard. Mechanical thresholds are screening rules, not guarantees or investment advice.</footer></div></main>}
