type Bar={t:number;o:number;h:number;l:number;c:number;v:number};
type YahooQuote={open?:Array<number|null>;high?:Array<number|null>;low?:Array<number|null>;close?:Array<number|null>;volume?:Array<number|null>};
type YahooChart={chart?:{result?:Array<{timestamp?:number[];indicators?:{quote?:YahooQuote[]}}>}};
const YF="https://query1.finance.yahoo.com/v8/finance/chart/";
const STOOQ="https://stooq.com/q/d/l/";
function etProgress(now=Date.now()){const p=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",hour12:false,hour:"2-digit",minute:"2-digit"}).formatToParts(now);const h=Number(p.find(x=>x.type==="hour")?.value||0),m=Number(p.find(x=>x.type==="minute")?.value||0),mins=h*60+m;return Math.max(.05,Math.min(1,(mins-570)/390))}
async function yahoo(ticker:string,interval:"1d"|"5m",range:string){
  const hosts=["query1.finance.yahoo.com","query2.finance.yahoo.com"];let last:unknown=null;
  for(const host of hosts){const c=new AbortController(),timer=setTimeout(()=>c.abort(),5000);try{
    const u="https://"+host+"/v8/finance/chart/"+encodeURIComponent(ticker)+"?interval="+interval+"&range="+range+"&includePrePost=false&events=div%2Csplits";
    const r=await fetch(u,{cache:"no-store",headers:{"User-Agent":"Squeeze-Race/1.0"},signal:c.signal});
    if(!r.ok)throw new Error("Yahoo chart HTTP "+r.status);
    return(await r.json()) as YahooChart;
  }catch(e){last=e}finally{clearTimeout(timer)}}
  throw last||new Error("Yahoo chart unavailable");
}
function bars(j:YahooChart):Bar[]{const x=j.chart?.result?.[0],q=x?.indicators?.quote?.[0],ts=x?.timestamp||[];if(!q)return[];return ts.map((t,i)=>({t:t*1000,o:Number(q.open?.[i]??NaN),h:Number(q.high?.[i]??NaN),l:Number(q.low?.[i]??NaN),c:Number(q.close?.[i]??NaN),v:Number(q.volume?.[i]??0)})).filter(x=>Number.isFinite(x.c)&&Number.isFinite(x.h))}
function isRth(ts:number){const p=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",hour12:false,hour:"2-digit",minute:"2-digit"}).formatToParts(ts);const h=Number(p.find(x=>x.type==="hour")?.value||0),m=Number(p.find(x=>x.type==="minute")?.value||0),v=h*60+m;return v>=570&&v<960}
export async function get20DayHistory(ticker:string){const now=Date.now();try{const daily=bars(await yahoo(ticker,"1d","3mo")).sort((a,b)=>b.t-a.t),todayKey=new Date(now).toLocaleDateString("en-US",{timeZone:"America/New_York"}),completed=daily.filter(b=>new Date(b.t).toLocaleDateString("en-US",{timeZone:"America/New_York"})!==todayKey).slice(0,20);if(completed.length<20)throw new Error("fewer than 20 completed daily bars");const breakout=Math.max(...completed.map(b=>b.h)),avgVolume=completed.reduce((a,b)=>a+b.v,0)/20,avgRange=completed.reduce((a,b)=>a+(b.h-b.l)/Math.max(b.c,0.000001),0)/20,prior5=completed.slice(0,5),prior20=completed,vol5=prior5.reduce((a,b)=>a+b.v,0)/Math.max(1,prior5.length),price20=completed.at(-1)?.c??null,intraday=bars(await yahoo(ticker,"5m","5d")).filter(b=>isRth(b.t)),today=intraday.filter(b=>new Date(b.t).toLocaleDateString("en-US",{timeZone:"America/New_York"})===todayKey),cumulative=today.reduce((a,b)=>a+b.v,0),rvol=avgVolume>0?cumulative/(avgVolume*etProgress(now)):null,price=today.at(-1)?.c??daily[0]?.c??null;const momentum5=prior5.length>=2&&prior5.at(-1)!.c>0?(prior5[0].c/prior5.at(-1)!.c-1)*100:null;const rangeCompression=prior5.length&&avgRange>0?prior5.reduce((a,b)=>a+(b.h-b.l)/Math.max(b.c,0.000001),0)/prior5.length/avgRange:null;const volumeAcceleration=avgVolume>0?vol5/avgVolume:null;const breakoutDistance=price!==null&&breakout>0?(price/breakout-1)*100:null;return{breakout,rvol,avgVolume,price,volume:cumulative,momentum5,rangeCompression,volumeAcceleration,breakoutDistance,observedAt:now,source:"Yahoo Finance chart (keyless)",freshness:"LIVE" as const}}catch{try{const u=STOOQ+"?s="+encodeURIComponent(ticker.toLowerCase()+".us")+"&d1="+new Date(Date.now()-120*86400000).toISOString().slice(0,10)+"&d2="+new Date().toISOString().slice(0,10)+"&i=d",r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error();const txt=await r.text(),rows=txt.trim().split(/\r?\n/).slice(1).map(x=>x.split(",")).filter(x=>x.length>=6).map(x=>({h:Number(x[2]),v:Number(x[5]),c:Number(x[4])})).filter(x=>Number.isFinite(x.h)),completed=rows.slice(-20);if(completed.length<20)throw new Error();const avg=completed.reduce((a,x)=>a+x.v,0)/20;return{breakout:Math.max(...completed.map(x=>x.h)),rvol:null,avgVolume:avg,price:completed.at(-1)?.c??null,volume:null,momentum5:null,rangeCompression:null,volumeAcceleration:null,breakoutDistance:null,observedAt:Date.now(),source:"Stooq daily fallback (keyless)",freshness:"SNAPSHOT" as const}}catch{return{breakout:null,rvol:null,avgVolume:null,price:null,volume:null,momentum5:null,rangeCompression:null,volumeAcceleration:null,breakoutDistance:null,observedAt:Date.now(),source:"Yahoo/Stooq history",freshness:"UNAVAILABLE" as const}}}}
