import {WATCHLIST} from "./config";import {evaluate} from "./rules";import {get20DayHistory} from "./history";import {getShortBundle} from "./short";import {getTradingViewFundamentals} from "./tradingview";
const histCache=new Map<string,{at:number;v:Awaited<ReturnType<typeof get20DayHistory>>}>(),shortCache=new Map<string,{at:number;v:Awaited<ReturnType<typeof getShortBundle>>}>();
async function mapLimit<T,R>(items:T[],limit:number,fn:(x:T)=>Promise<R>){const out:R[]=[];let n=0;async function worker(){while(n<items.length){const i=n++;out[i]=await fn(items[i])}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}\nasync function cachedHistory(t:string){const c=histCache.get(t);if(c&&Date.now()-c.at<60000)return c.v;const v=await get20DayHistory(t);histCache.set(t,{at:Date.now(),v});return v}
async function cachedShort(t:string,tv:Awaited<ReturnType<typeof getTradingViewFundamentals>>){const c=shortCache.get(t);if(c&&Date.now()-c.at<300000)return c.v;const v=await getShortBundle(t,tv);shortCache.set(t,{at:Date.now(),v});return v}
export async function getMarket(){
  const now=Date.now(),results=await Promise.all(WATCHLIST.map(async x=>{const[h,s]=await Promise.all([cachedHistory(x.ticker),cachedShort(x.ticker,tv)]),price=h.price??s.price,avgVolume=h.avgVolume??null,currentVolume=h.volume??s.volume,rvol=h.rvol??(avgVolume&&avgVolume>0&&currentVolume!==null?currentVolume/(avgVolume*1):null),floatTurnover=s.float&&currentVolume!==null?currentVolume/s.float*100:null;const sources:Record<string,{value:number|null;source:string;observedAt:number|null;freshness:"LIVE"|"SNAPSHOT"|"LAGGED"|"UNAVAILABLE"}>={...s.sources,price:{value:price,source:h.source,observedAt:h.observedAt,freshness:h.freshness},breakout:{value:h.breakout,source:h.source,observedAt:h.observedAt,freshness:h.freshness},rvol:{value:rvol,source:h.rvol!==null?h.source:(s.volume!==null?"TradingView public scanner + "+h.source:"Yahoo/Stooq history"),observedAt:h.rvol!==null?h.observedAt:(s.volume!==null?Date.now():h.observedAt),freshness:h.rvol!==null?h.freshness:(s.volume!==null?"LIVE":"UNAVAILABLE") as any},floatTurnover:{value:floatTurnover,source:h.source+" + TradingView float",observedAt:h.observedAt,freshness:h.freshness}};const base={ticker:x.ticker,price,breakout:h.breakout,rvol,si:s.si,dtc:s.dtc,ctb:s.ctb,avail:s.avail,ftd:s.ftd,svd:s.svd,ctbFreshness:s.sources.ctb.freshness,availFreshness:s.sources.avail.freshness,ftdFreshness:s.sources.ftd.freshness,marketCap:s.marketCap,float:s.float,floatTurnover,updatedAt:now,sources,provider:"Yahoo/Stooq + FINRA + TradingView + "+s.sources.ctb.source+" + SEC",freshness:price!==null&&h.breakout!==null&&s.si!==null?"PARTIAL":"DATA-GAP"};const ev=evaluate(base);return{...base,phase:ev.phase,reasons:ev.reasons}}));
  const fields=["si","dtc","ctb","avail","ftd","svd","price","breakout","rvol","float","marketCap"] as const;const coverage=Object.fromEntries(fields.map(f=>[f,results.filter(x=>x[f]!==null).length]));const phaseCounts=Object.fromEntries([...new Set(results.map(x=>x.phase))].map(p=>[p,results.filter(x=>x.phase===p).length]));
  const borrowSources=new Set(results.flatMap(x=>[x.sources.ctb.source,x.sources.avail.source]));const mockBorrow=[...borrowSources].some(x=>x.includes("MOCK_IBKR"));const liveBorrow=[...borrowSources].some(x=>x.includes("IBorrowDesk")&&!x.includes("public"));const publicBorrow=[...borrowSources].some(x=>x.includes("IBorrowDesk public"));
  const providerStatus={finraShortInterest:coverage.si>0,finraShortVolume:coverage.svd>0,tradingViewFundamentals:coverage.float>0,iborrowDesk:publicBorrow,borrowFeed:mockBorrow?"MOCK_IBKR":publicBorrow?"PUBLIC_IBORROWDESK":"UNAVAILABLE",secFtd:coverage.ftd>0,priceHistory:coverage.price>0};
  const coverageComplete=fields.every(f=>coverage[f]===results.length);return{signals:results,symbolCount:results.length,expectedSymbolCount:WATCHLIST.length,source:mockBorrow?"controlled mock provider mesh": "keyless public provider mesh",borrowProvider:mockBorrow?"MOCK_IBKR":publicBorrow?"PUBLIC_IBORROWDESK":liveBorrow?"LIVE_IBKR":"UNAVAILABLE",timestamp:now,live:!mockBorrow,coverageComplete,coverage,phaseCounts,providerStatus,error:results.some(x=>x.phase==="DATA-GAP")?"Some required fields remain unavailable; no positive squeeze state is fabricated":undefined}
}
