export type PressureBand="EXTREME"|"HIGH"|"ELEVATED"|"NEUTRAL"|"WEAK"|"DATA-GAP";
export type PressureInput={si:number|null;siChangePct:number|null;dtc:number|null;ctb:number|null;avail:number|null;ftd:number|null;svd:number|null;rvol:number|null;breakoutDistance:number|null;momentum5:number|null;rangeCompression:number|null;volumeAcceleration:number|null;floatTurnover:number|null;marketCap:number|null;ctbFreshness?:string;availFreshness?:string;ftdFreshness?:string;borrowTrusted?:boolean};
const clamp=(x:number)=>Math.max(0,Math.min(100,x));
const freshness=(v:number|null,f?:string)=>v!==null&&f!=="LAGGED"&&f!=="UNAVAILABLE";
export function scorePressure(x:PressureInput){
 if(x.si===null||x.dtc===null||x.rvol===null||x.breakoutDistance===null)return{score:null,band:"DATA-GAP" as PressureBand,dataCoveragePct:0,qualityFlags:["INSUFFICIENT_CORE_DATA"],reasons:["insufficient core data for pressure score"],components:{}};
 const c:any={};c.shortInterest=clamp((x.si-10)*2);c.siTrend=x.siChangePct===null?50:clamp(50+x.siChangePct*4);c.daysToCover=clamp((x.dtc-2)*8);c.volume=clamp((x.rvol-1)*22);c.breakout=clamp(50+x.breakoutDistance*10);c.momentum=clamp(50+(x.momentum5??0)*4);c.borrow=freshness(x.ctb,x.ctbFreshness)?clamp((x.ctb!-2)*7):0;c.availability=freshness(x.avail,x.availFreshness)?clamp(100-(x.avail!/10000)):0;c.ftd=x.ftd===null?0:clamp(x.ftd*15);c.shortVolume=x.svd===null?0:clamp((x.svd+2)*7);c.compression=x.rangeCompression===null?50:clamp((1-(x.rangeCompression||1))*100);c.volumeAcceleration=x.volumeAcceleration===null?50:clamp((x.volumeAcceleration-1)*50);c.floatTurnover=x.floatTurnover===null?0:clamp(x.floatTurnover*2);
 const weights={shortInterest:.12,siTrend:.07,daysToCover:.11,volume:.13,breakout:.12,momentum:.09,borrow:x.borrowTrusted===false?0:.10,availability:x.borrowTrusted===false?0:.08,ftd:.05,shortVolume:.05,compression:.05,volumeAcceleration:.05,floatTurnover:.04};
 let score=0,weight=0;for(const [k,w] of Object.entries(weights)){if(c[k]!==null){score+=c[k]*w;weight+=w}}score=weight?score/weight:0;const required=[x.si,x.siChangePct,x.dtc,x.rvol,x.breakoutDistance,x.ctb,x.avail,x.ftd,x.svd,x.momentum5,x.rangeCompression,x.volumeAcceleration,x.floatTurnover];const completeness=required.filter(v=>v!==null).length/required.length;const freshnessPenalty=(x.borrowTrusted===false?0.05:0)+(x.ctbFreshness==="LAGGED"?0.08:0)+(x.availFreshness==="LAGGED"?0.08:0)+(x.ftdFreshness==="LAGGED"?0.12:0);const dataCoveragePct=Number((completeness*100).toFixed(1));
 const reasons:string[]=[];if(x.si>=20)reasons.push("high short-interest load");if((x.siChangePct??0)>=10)reasons.push("short interest rising >=10% vs prior settlement");if(x.dtc>=5)reasons.push("covering pressure via DTC");if(x.rvol>=2)reasons.push("volume expansion");if((x.breakoutDistance??-99)>=0)reasons.push("at/above 20-day breakout");if((x.ctb??0)>=5&&freshness(x.ctb,x.ctbFreshness))reasons.push("borrow fee stress");if((x.avail??1e12)<=500000&&freshness(x.avail,x.availFreshness))reasons.push("restricted availability");if((x.ftd??0)>=1)reasons.push("elevated FTD/float");if((x.svd??0)>=5)reasons.push("short-volume divergence");if((x.volumeAcceleration??0)>=1.5)reasons.push("accelerating volume");if((x.rangeCompression??2)<.75)reasons.push("range compression");
 const band:PressureBand=score===null?"DATA-GAP":score>=80?"EXTREME":score>=65?"HIGH":score>=50?"ELEVATED":score>=35?"NEUTRAL":"WEAK";
 const qualityFlags:string[]=[];
 if(x.borrowTrusted===false)qualityFlags.push("BORROW_MOCK_OR_UNTRUSTED");
 if(x.ctbFreshness==="LAGGED"||x.availFreshness==="LAGGED")qualityFlags.push("BORROW_STALE");
 if(x.ftdFreshness==="LAGGED")qualityFlags.push("FTD_STALE");
 if(x.si!==null&&x.si>100)qualityFlags.push("SI_OVER_100_ANOMALY");
 return{score:score===null?null:Number(score.toFixed(1)),band,dataCoveragePct,qualityFlags,reasons,components:c};
}
